version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: parking_postgres
    environment:
      POSTGRES_DB: parking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: parking_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: parking_db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  postgres_data:
  node_modules: